/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const CrmServiceMap = {
"closecom": import("./closecom/lib/CrmService"),
"pipedrive-crm": import("./pipedrive-crm/lib/CrmService"),
"zoho-bigin": import("./zoho-bigin/lib/CrmService"),
"zohocrm": import("./zohocrm/lib/CrmService"),
};